# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

# See https://jsfiddle.net/GuanglinDu/feoxt8yL/
#$ ->
#  $('.collapse').on 'show.bs.collapse', ->
#    $('.collapse.in').collapse 'hide'

# How to add plus minus symbol to a bootstrap accordion
# http://stackoverflow.com/questions/22242422/how-to-add-plus-minus-symbol-to-a-bootstrap-accordion
# Coverted by http://www.js2.coffee
# generated by js2coffee 2.0.4
$ ($) ->
  $('[data-toggle="collapse"]').on 'click', ->
    $this = $(this)
    $parent = if typeof $this.data('parent') != 'undefined' then $($this.data('parent')) else undefined
    if $parent == undefined
      ### Just toggle my  ###
      $this.find('.glyphicon').toggleClass 'glyphicon-plus glyphicon-minus'
      return true

    ### Open element will be close if parent !== undefined ###
    currentIcon = $this.find('.glyphicon')
    currentIcon.toggleClass 'glyphicon-plus glyphicon-minus'
    $parent.find('.glyphicon').not(currentIcon).removeClass('glyphicon-minus').addClass 'glyphicon-plus'
    return
  return
